[config]
# models
model="anthropic/claude-3-5-sonnet-20241022"
fallback_models=["anthropic/claude-3-5-haiku-20241022"]
# configuration
response_language="ko-KR"
# token limits
max_model_tokens = 20000

[pr_reviewer] # /review - 기본 알고리즘 코드 리뷰
# enable/disable features - 알고리즘 코드리뷰에 과한 설정들 끄기
require_estimate_effort_to_review=false
require_security_review=false
require_ticket_analysis_review=false
# general options
extra_instructions = """
Focus on algorithmic and performance improvements in JS/TS code.
1. Analyze time and space complexity; suggest improvements (e.g., O(n) → O(1) if possible).
2. Propose alternative data structures or patterns (Set/Map, two pointers, sliding window, etc.).
3. Identify potential edge cases and provide at least 2 counterexamples.
4. Suggest minimal code changes that directly improve correctness or efficiency.
Do not focus on cosmetic or style-only changes here.
"""
# review labels
enable_review_labels_security=false
enable_review_labels_effort=false
# specific configurations for incremental review (/review -i)
enable_intro_text=false

[pr_description] # /describe
publish_labels=true
publish_description_as_comment=false
publish_description_as_comment_persistent=false
enable_pr_diagram=false
# changes walkthrough section
enable_semantic_files_types=false

[pr_code_suggestions] # /improve - 코드 개선 (좀 더 우아한 코드)
extra_instructions = """
Provide improvements to make the code more elegant and maintainable.
Focus on readability, naming, modularity, and idiomatic JS/TS practices.
Do not suggest trivial style-only changes unless they improve clarity or performance.
Always provide concrete refactored code snippets, not abstract advice.
"""
# enable to apply suggestion (maybe premium feature)
apply_suggestions_checkbox=false

[custom_labels]
enable_custom_labels=true
[custom_labels."leetcode"]
description = "Use when the PR contains changes in the Leetcode directory"
[custom_labels."programmers"]
description = "Use when the PR contains changes in the Programmers directory"

[github]
