name: PR Labeler

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v6
        with:
          repo-token: ${{ secrets.ASSISTANT_GITHUB_TOKEN }}
          sync-labels: true
